### ISSUE TITLE
Automatically set roles for members based on their Amari level

### ISSUE THREAD

**Issue by lynnntropy** [lynnntropy/shinoa#73]
We could potentially do this by pulling data from Amari directly:

https://docs.amaribot.com/api/api/guild-raw-leaderboard-guild
https://amaribot.js.org/

**Comment by lynnntropy** [comment]
This is blocked for a bit until we get an API key for Amari

**Comment by thewilloftheshadow** [comment]
Hi there! I'm Shadow, the AmariBot staff member for the API. You aren't in our support server from what I can see, so I just wanted to let you that you were approved for the AmariBot API, and you can access the dashboard to get your key for the amaribot.js package (or whatever you choose to use) at this link:
https://amaribot.com/developer

**Comment by lynnntropy** [comment]
@thewilloftheshadow Thank you!
